source "https://rubygems.org"

gem "jekyll", "~> 4.4.1" 
gem "webrick"
gem "just-the-docs", "0.10.1" # If you're using Just the Docs theme
gem "webrick"
gem "jekyll-sass-converter"
gem "public_suffix"
gem "rouge"
gem "i18n"
gem "mercenary"
gem "terminal-table"
gem "sass-embedded"
