name: CI

on:
  [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Update Bundler
        run: gem install bundler:2.5.9

      - name: Install dependencies
        working-directory: docs
        run: bundle install --jobs 4 --retry 3

      - name: Build site with Jekyll
        working-directory: docs
        run: bundle exec jekyll build
