jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install
        working-directory: ${{ github.workspace }}

      - name: Build Jekyll site
        run: bundle exec jekyll build
        working-directory: ${{ github.workspace }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
          token: ${{ secrets.GITHUB_TOKEN }}